---
  - name: Shell Examples
    hosts: all
    become: true
    tasks:

    - name: Dir list and write to file
      shell:
        " ls -ld /home/*sing* > /tmp/out.txt "
      register: lsout
      tags: lsout

    - name: Display the file
      shell: cat /tmp/out.txt
      register: displaylist
      
    - debug: msg="{{displaylist.stdout_lines}}"
