---
- hosts: all
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: no
  connection: ssh

  tasks:
  - debug:
      msg:
      - "ansible_distribution {{ hostvars[inventory_hostname].ansible_distribution }}"
      - "major version {{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
      - "version {{ hostvars[inventory_hostname].ansible_distribution_version }}"
...

